### ISSUE TITLE
Error when upgrading to Magento 2.2

### ISSUE THREAD

**Issue by mve0991** [mailcampaigns/Magento2Connector#1]
Leading backslash in class names is not allowed and is resulting an error when upgrading to Magento 2.2. Therefore the block class references in view/frontend/layout/default.xml and view/frontend/layout/checkout_onepage_success.xml should be changed from \Magento\Framework\View\Element\Template to Magento\Framework\View\Element\Template.

**Comment by barryvdh** [comment]
Pull request submitted in #2
