### ISSUE TITLE
PHP 7.4 support in 2.2 branch?

### ISSUE THREAD

**Issue by timkoopmans50** [mailcampaigns/Magento2Connector#15]
Hey Team, 

PHP 7.4 support is missing in the 2.2 Branch, is there a specific reason for this?

**Comment by timkoopmans50** [comment]
@mailcampaigns ?

**Comment by m-a-x-s-e-e-l-i-g** [comment]
Hey Tim,

Our busy schedules haven't allowed us to complete this task yet. 
We have it on our backlog. 
Please let my dear colleague [Jessica](mailto:support@mailcampaigns.nl) know if PHP 7.4 support is of vital importance for your webshop at [support@mailcampaigns.nl](mailto:support@mailcampaigns.nl)

**Comment by timkoopmans50** [comment]
It is **absolutely vital for pretty much all webshops using this module!** 

https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html
https://www.php.net/supported-versions.php

This should be a prio 1 issue.

**Comment by mailcampaigns** [comment]
Issue solved in [2.2.0-RC14](https://github.com/mailcampaigns/Magento2Connector/releases/tag/2.2.0-RC14)
