### ISSUE TITLE
Final 2.2 tag

### ISSUE THREAD

**Issue by Swahjak** [mailcampaigns/Magento2Connector#21]
We have pretty strict composer settings, which do not allow us to install RC tags, but 2.2 never left RC. Would it be possible to get a 'final' tag on 2.2 (or even a 2.3).

**Comment by m-a-x-s-e-e-l-i-g** [comment]
Hi Peep,
Voor jullie webshop is deze module niet nodig aangezien we hier iets nieuws voor hebben gemaakt wat jullie REST API gaat gebruiken. Ik wil je vragen om alvast de volgende module te installeren: https://github.com/mailcampaigns/magento2-subscriber-api
Deze maakt newsletter subscribers beschikbaar in jullie API zodat we ook deze kunnen synchroniseren.
Vervolgstappen zul je te horen krijgen via Jordie of Lauren.
