### ISSUE TITLE
MailCampaigns popup doesn't function (anymore)

### ISSUE THREAD

**Issue by ennostuurman** [mailcampaigns/Magento2Connector#29]
**Steps to reproduce:**

Enter email in the MailCampagins popup and click submit

Expected result:
email address is registered (subscription success message)

Actual result:
Nothing happens

**Fix**

The module popup script has worked before but since recently not anymore. 
Quick fix is to remove the tracker_js script completely `<referenceBlock name="tracker_js" remove="true"/>`
and replace this with a the following snippet as MailCampaigns support suggested.

```<script type='text/javascript'>
    (function(d,t) {
        _mctc = {'onload': function() { this.mctrkDocumentLoad(); }};
        var s=d.getElementsByTagName(t)[0], js=d.createElement(t); js.async=1;
        js.src='https://interface.mailcampaigns.nl/interface/popup.php?ref=..........';
        s.parentNode.insertBefore(js,s);
    })(document,'script');
</script>
```

Can you please update the module so the popup script will work as expected and without required custom overrides?

**Comment by m-a-x-s-e-e-l-i-g** [comment]
Heb je in MailCampaigns de volgende setting aanstaan?
![image](https://github.com/mailcampaigns/Magento2Connector/assets/7907436/4087f2a2-f681-46be-a51b-d141c936bd7d)
Deze setting zorgt ervoor dat het door jou genoemde script word ingeladen.

**Comment by ennostuurman** [comment]
bedankt @m-a-x-s-e-e-l-i-g voor de feedback. Ik ga dit met de klant checken want ik heb zelf geen toegang tot het Mailcampaigns dashboard.
