### ISSUE TITLE
main.CRITICAL: Class MailCampaigns\Connector\Helper\MailCampaigns_API does not exist

### ISSUE THREAD

**Issue by nanhe88** [mailcampaigns/Magento2Connector#6]
I installed the module on my magento (2.3.0 version) application. It installed successfully but when I try to add product to cart. It's throwing error on product page - We can't add this item to your shopping cart right now.

**Error in exception log  -** 

main.CRITICAL: Class MailCampaigns\Connector\Helper\MailCampaigns_API does not exist {"exception":"[object] (ReflectionException(code: 0): Class MailCampaigns\\Connector\\Helper\\MailCampaigns_API does not exist at /var/www/html/magento23/vendor/magento/framework/Code/Reader/ClassReader.php:35, ReflectionException(code: 0): Class MailCampaigns\\Connector\\Helper\\MailCampaigns_API does not exist at /var/www/html/magento23/vendor/magento/framework/Code/Reader/ClassReader.php:29)"} []

Is this module not compatible with Magento version 2.3.0 or what can be issues behind this error?

**Comment by netzwelt-nishu** [comment]
Hi,
I am also facing the same issue in my Magento 2.3.0 Env. Is there any solution for the issue. ? 
Thanks!

**Comment by mailcampaigns** [comment]
Hi, have you installed in the Vendor folder with composer?

**Comment by netzwelt-nishu** [comment]
Hi, no i have uploaded this module zip file in app/code folder. can you provide me composer way to install the extension.

**Comment by mailcampaigns** [comment]
composer require mailcampaigns/magento2connector

**Comment by netzwelt-nishu** [comment]
I got below message when i tried this from composer:
Package mailcampaigns/magento2connector at version  has a PHP requirement incompatible with your PHP version (7.2.15)
