### ISSUE TITLE
2.2.0-rc.1 tracker.js possible issues

### ISSUE THREAD

**Issue by igorwulff** [mailcampaigns/Magento2Connector#9]
Hello MailCampaigns/Bert,

I'm currently looking at the 2.2.0-rc1 release. We already reported an issue with the tracker.js in the past. In short:
`The tracker_js.phtml is cacheable and the script output will be cached in the block cache and FPC. The best approach would be to (if needed) use the available data in the LocalStorage to set unique values per customer.`

The data send to interface.mailcampaigns.nl is build up by a postdata variable.
This postdata variable is composed of a store_id, customer_id, visitor_id, and a product_id.

Based on how FPC is implemented, the store_id and product_id should work fine in the current implementation. Visitor_id will also work fine, since it is always a 0 value.

However customer_id is retrieved from an instance of Magento\Customer\Model\Customer and using getId(). This will cause tracking for logged-in customer go wrong in a lot of cases, since cache is build up and the script will be part of the cache, with sometimes having a customer_id from a previous user/transaction.

Now either we should just remove the customer_id tracking, which is something we probably don't want or retrieve this data from a source that's already available. Since product data and customer data is already available in the LocalStorage we can benefit from it and retrieve our data from there. 
Please don't use a holepunch for this, because that will create a performance hit which we don't want.

Can you also please change ObjectManager calls on the script?

Now perhaps we are overlooking something in this case, if that is so please explain how this is working so we can get an better understanding of it.

**Comment by igorwulff** [comment]
Hi Bert or any other developer from MailCampaigns,

Can you give a response to my query above?

I also noticed the v2.2.0-rc.1 tag not being in packagist, can that be resolved? When do you expect a stable release?

**Comment by mailcampaigns** [comment]
> Hi Bert or any other developer from MailCampaigns,
> 
> Can you give a response to my query above?
> 
> I also noticed the v2.2.0-rc.1 tag not being in packagist, can that be resolved? When do you expect a stable release?

Hi Igor,

Thank you for your detailed feedback.

I see what you mean regarding the potential caching issue. I will fix this by using the existing data from the LocalStorage as you suggested.

As for the ObjectManager calls, I will look into this as well.

Were there any other issues you've come across in the meanwhile?

I expect to have these issues fixed somewhere in the next week so we can proceed to release a stable version after that as soon as possible for our client.

Again, many thanks for your feedback and suggestions!

Regards,

Bert

**Comment by mailcampaigns** [comment]
> I also noticed the v2.2.0-rc.1 tag not being in packagist, can that be resolved? When do you expect a stable release?

I see, this is strange since normally this would be updated automatically through GitHub, I'll have a look!

**Comment by igorwulff** [comment]
Hi Bert,

Thanks! The module is looking very good now, besides this issue. With the tag in packagist I can deploy this to acceptance for further testing.

**Comment by mailcampaigns** [comment]
> Hi Bert,
> 
> Thanks! The module is looking very good now, besides this issue. With the tag in packagist I can deploy this to acceptance for further testing.

Good to hear, thank you!

I've managed to find out and fix the issue with Packagist: Apparently they don't like the format of the version tag (which is strange since Semantic Versioning uses the format that Packagist does not recognize: https://semver.org/spec/v2.0.0-rc.1.html, ah well..)

I have changed it to `2.2.0-RC1` and it's now listed: https://packagist.org/packages/mailcampaigns/magento2connector#2.2.0-RC1

**Comment by mailcampaigns** [comment]
Hi Igor,

I've resolved this issue by using the customer data from the Local Storage. The fix is included in [2.2.0-RC2](https://github.com/mailcampaigns/Magento2Connector/releases/tag/2.2.0-RC2)

As for your request regarding the ObjectManager:
> Can you also please change ObjectManager calls on the script?
I will create a new issue for this as I did not have the time yet to make this change but agree this would be better.
